#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") APK_FILE

Launches an application on a connected Android device using its APK.

This script determines the package ID from the APK and uses 'adb monkey'
to launch the main activity.

Arguments:
  APK_FILE    Path to the APK file of the application to launch.

Options:
  --help      Display this help message and exit

Environment:
  ANDROID_SERIAL  Serial number of device to connect to (see 'adb devices -l').
                  To target a specific device, use:
                    env ANDROID_SERIAL=<serial> $(basename "$0")

Examples:
  # Launch the application corresponding to an APK
  $(basename "$0") /path/to/your/app.apk
EOF
  exit 0
}

if [[ "$1" == "--help" ]]; then
  usage
fi

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo >&2 "$(basename "$0"): $1 not found"
    exit 127
  }
}

require adb
require apkanalyzer

if [ -z "$1" ]; then
  usage
fi

if [ ! -f "$1" ]; then
  echo "$(basename "$0"): $1: No such file or directory" >&2
  exit 1
fi

adb exec-out monkey -p "$(apkanalyzer manifest application-id "$1")" -c android.intent.category.LAUNCHER 1
