#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") APK_FILE

Extracts and displays the launcher icon file from an APK.

This script reads the 'application-icon' attribute from the APK's manifest
and then extracts that file's content.

Arguments:
  APK_FILE    Path to an APK file or a ZIP archive containing a base split APK.

Options:
  --help      Display this help message and exit

Examples:
  # Display the launcher icon file from an APK
  $(basename "$0") /path/to/your/app.apk

  # Can also be used with ZIP archives
  $(basename "$0") /path/to/your/app.zip
EOF
  exit 0
}

if [[ "$1" == "--help" ]]; then
  usage
fi

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo >&2 "$(basename "$0"): $1 not found"
    exit 127
  }
}

require apk-cat-file
require aapt
require unzip

if [ -z "$1" ]; then
  usage
fi

# Standard Code for Base APK Extraction
if [[ $1 == *.zip ]]; then
  TMPDIR=$(mktemp -d)
  trap 'rm -rf -- "$TMPDIR"' EXIT
  unzip -q -j "$1" '*-base-split.apk' -d "$TMPDIR"
  BASEAPKS=("$TMPDIR"/*-base-split.apk)
  BASEAPK="${BASEAPKS[0]}"
  if [ ! -f "$BASEAPK" ]; then
    echo "$(basename "$0"): *-base-split.apk not found in zip, aborting" >&2
    exit 1
  fi
else
  BASEAPK="$1"
fi

LAUNCHER=$(aapt d badging "$BASEAPK" | awk -F\' '/^application:/ {print $4}')

if [ -n "$LAUNCHER" ]; then
  apk-cat-file "$1" "$LAUNCHER"
fi
