#!/usr/bin/env bash

# Symlinks files stored in $HOME/.config (i.e. in a subversion repository)
# to their correct location--mostly $HOME, but a few other directories
# as well, like $HOME/.subversion/config.
#
# This command is idempotent; you can safely run it more than once.

# From http://stackoverflow.com/a/246128/11543
SRCDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -d "$1" ]; then
  DSTDIR="$1"
else
  DSTDIR="$( cd -P "$( dirname "${SRCDIR}" )" && pwd )"
fi

# 1. Runs the passed command.
# 2. Echos the executed command.

function x {

  "$@"

  while [ "$1" ]; do

    if [[ "$1" =~ " " ]]; then
      echo -n "'$1'"
    else 
      echo -n "$1"
    fi

    if [ ! -z "$2" ]; then
      echo -n " "
    else
      echo
    fi

    shift

  done

}

for f in gls ls ; do

  if [ -x "$(which $f)" ]; then
     LS=$f
     break
  fi

done

cd "$SRCDIR/home"

for f in `$LS -AB` ; do # substitution not supported with the $(...) style

  if [ "$f" = "CVS" ]; then
    continue
  fi

  if [ "$f" = ".svn" ]; then
    continue
  fi
  
  if [ "$f" = ".git" ]; then
    continue
  fi
  
  if [[ "$f" =~ "~$" ]]; then
    continue
  fi
  
  x ln -sf "${SRCDIR#$DSTDIR/}/home/$f" "$DSTDIR"

done

if [ `which svn` ]; then
  x rm -f "$DSTDIR/.subversion/config"
  x mkdir -p "$DSTDIR/.subversion"
  x ln -sf "$SRCDIR/etc/subversion/config" "$DSTDIR/.subversion/config"
fi

if [ `which cpan` ]; then  
  x rm -f "$DSTDIR/.cpan/CPAN/MyConfig.pm"
  x mkdir -p "$DSTDIR/.cpan/CPAN"
  x ln -sf "$SRCDIR/etc/CPAN/MyConfig.pm" "$DSTDIR/.cpan/CPAN/MyConfig.pm"
fi

if [ `which subl` ]; then

  if [ `$DSTDIR/.platform` = "linux" ]; then
    DST="$DSTDIR/.config/sublime-text-2/Packages/User"
  else
    DST="$DSTDIR/Library/Application Support/Sublime Text 2/Packages/User"
  fi
      
  x mkdir -p "$DST"
  x rm -f "$DST/Preferences.sublime-settings"
  x ln -sf "$SRCDIR/etc/subl/Preferences.sublime-settings" "$DST/Preferences.sublime-settings"

  for d in Linux OSX Windows ; do
    x rm -f "$DST/Default ($d).sublime-keymap"
    x ln -sf "$SRCDIR/etc/subl/Default.sublime-keymap" "$DST/Default ($d).sublime-keymap"
  done
  
fi

if [ -d "$DSTDIR/Library" ]; then

  x rm -f "$DSTDIR/Library/KeyBindings"
  x ln -sf "$SRCDIR/etc/KeyBindings" "$DSTDIR/Library/KeyBindings"

fi
