#!/usr/bin/env bash

# Symlinks files stored in $HOME/.config (i.e. in a subversion repository)
# to their correct location--mostly $HOME, but a few other directories
# as well, like $HOME/.subversion/config.

CONFIGROOT=${1:-$HOME/.config}

# Runs the passed command, and also echo it out.

function x {

  "$@"

  while [ "$1" ]; do

    if [[ "$1" =~ " " ]]; then
      echo -n "'$1'"
    else 
      echo -n "$1"
    fi

    if [ ! -z "$2" ]; then
      echo -n " "
    else
      echo
    fi

    shift

  done

}

for f in gls ls ; do
  if [ -x "$(which $f)" ]; then
     LS=$f
     break
  fi
done

cd "$CONFIGROOT/home"

for f in `$LS -AB` ; do # substitution now support in $(...) mode

  if [ "$f" = "CVS" ]; then
    continue
  fi

  if [ "$f" = ".svn" ]; then
    continue
  fi
  
  if [ "$f" = ".git" ]; then
    continue
  fi
  
  x ln -sf ".config/home/$f" "$HOME"

done

if [ ! -h "$HOME/.subversion/config" ]; then

  x rm -f "$HOME/.subversion/config"
  x mkdir -p "$HOME/.subversion"
  x ln -sf "$CONFIGROOT/etc/subversion/config" "$HOME/.subversion/config"
  
fi

if [ ! -h "$HOME/.cpan/CPAN/MyConfig.pm" ]; then

    x rm -f "$HOME/.cpan/CPAN/MyConfig.pm"
    x mkdir -p "$HOME/.cpan/CPAN"
    x ln -sf "$CONFIGROOT/etc/CPAN/MyConfig.pm" "$HOME/.cpan/CPAN/MyConfig.pm"

fi
