#!/bin/bash

PLATFORM=$($HOME/.platform)

case $PLATFORM in

  darwin)
    READLINK="greadlink -f"
    ;;
    
  *)
    READLINK="readlink -f"
    ;;
    
esac

CONFIGROOT="${CONFIGROOT:-$(dirname $($READLINK $BASH_SOURCE))}"

curl -sS https://getcomposer.org/installer | php -d detect_unicode=off -- --install-dir=$CONFIGROOT/bin

if [ -e $CONFIGROOT/bin/composer.phar ]; then
  mv $CONFIGROOT/bin/composer.phar $CONFIGROOT/bin/composer
  chmod +x $CONFIGROOT/bin/composer
fi

curl -sS http://cs.sensiolabs.org/get/php-cs-fixer.phar -o $CONFIGROOT/bin/php-cs-fixer
