#!/bin/bash

PLATFORM=$($HOME/.platform)

case $PLATFORM in

  darwin)
    READLINK="greadlink -f"
    ;;
    
  *)
    READLINK="readlink -f"
    ;;
    
esac

CONFIGROOT="${CONFIGROOT:-$(dirname $($READLINK $BASH_SOURCE))}"

#wget -O $CONFIGROOT/etc/z.sh https://raw.github.com/rupa/z/master/z.sh
#wget -O $CONFIGROOT/etc/git-prompt.sh 'http://git.kernel.org/?p=git/git.git;a=blob_plain;f=contrib/completion/git-prompt.sh;hb=HEAD'
#wget -O $CONFIGROOT/etc/git-completion.sh 'http://git.kernel.org/?p=git/git.git;a=blob_plain;f=contrib/completion/git-completion.bash;hb=HEAD'

curl -sS https://getcomposer.org/installer | php -d detect_unicode=off -- --install-dir=$CONFIGROOT/bin

if [ -e $CONFIGROOT/bin/composer.phar ]; then
  mv $CONFIGROOT/bin/composer.phar $CONFIGROOT/bin/composer
  chmod +x $CONFIGROOT/bin/composer
fi
