#!/bin/bash

# Checks whether composer.json has changed after checkout, in which
# case you probably need to run 'composer install'.

# TODO Support a separate "composer" binary, instead of expecting "composer.phar" to exist

[ ! -f composer.json ] && exit

[ ! -f composer.phar ] && curl -s http://getcomposer.org/installer | php >/dev/null

# -e is supposed to inhibit all output but it doesn't...
( git cat-file -e "$1:composer.lock" >/dev/null 2>&1 ) && ( git cat-file -e "$2:composer.lock" >/dev/null 2>&1 ) && ( git diff --quiet "$1:composer.lock" "$2:composer.lock" ) && exit

if [ "$GIT_COMPOSER_STALE" == "warn" ]; then
  echo "composer: composer.lock changed on checkout; consider running 'php composer.phar install'"
else
  php composer.phar install
fi
