#!/bin/bash

# Checks whether composer.json has changed after checkout, in which
# case you probably need to run 'composer install'.

# See https://github.com/composer/composer/pull/1083

[ ! -f composer.json ] && exit

PREV_COMMIT=$1
POST_COMMIT=$2

[[ '0000000000000000000000000000000000000000' == $PREV_COMMIT ]] && exit

git diff --quiet $PREV_COMMIT..$POST_COMMIT composer.lock && exit

echo "composer: composer.lock changed on checkout; consider running 'composer install'"
