#!/usr/bin/env bash

require() { hash "$@" || exit 127; }

require adb

# Check if device is available
if [ "$(adb get-state 2>/dev/null)" != "device" ]; then
  echo "error: no device connected" >&2
  exit 1
fi

# Adds dynamic information from the status bar

adb exec-out am broadcast -a com.android.systemui.demo -e command exit
adb exec-out settings put global sysui_demo_allowed 0

# Disables the "Show touches" option

adb exec-out settings put system show_touches 0
