#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0")

Displays Wear Health Services (WHS) dumpsys information from an adb-connected
device.

Options:
  --help      Display this help message and exit

Environment:
  ANDROID_SERIAL  Serial number of device to connect to (see 'adb devices -l').
EOF
  exit 0
}

if [[ "$1" == "--help" ]]; then
  usage
fi

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo >&2 "$(basename "$0"): $1 not found"
    exit 127
  }
}

require adb

SERVICES=$(adb exec-out dumpsys activity service com.google.android.wearable.healthservices | grep ^SERVICE | awk '{ print $2 }')

for s in $SERVICES; do
  printf "### %s ###\n" "$s"
  echo
  adb exec-out dumpsys activity services "$s" # generic (system) service metadata
  echo
  adb exec-out dumpsys activity service "$s" # service specific debug output
  echo
done
