#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Lists installed packages on the connected device.
By default, lists only user-installed (third-party) packages.

Options:
  --all       List all packages (including system apps)
  --help      Display this help message and exit

Environment:
  ANDROID_SERIAL  Serial number of device to connect to (see 'adb devices -l').
EOF
  exit 0
}

# Parse args
all_apps=0

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --all) all_apps=1 ;;
    --help) usage ;;
    *)
      echo "$(basename "$0"): unknown option '$1'" >&2
      exit 1
      ;;
  esac
  shift
done

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo >&2 "$(basename "$0"): $1 not found"
    exit 127
  }
}

require adb

if ! adb get-state >/dev/null 2>&1; then
  if [[ -n "$ANDROID_SERIAL" ]]; then
    echo "$(basename "$0"): device '$ANDROID_SERIAL' not available" >&2
  else
    echo "$(basename "$0"): no device connected" >&2
  fi
  exit 1
fi

if ((all_apps)); then
  adb exec-out pm list packages | grep '^package:' | cut -b 9- | sort
else
  adb exec-out pm list packages -3 | grep '^package:' | cut -b 9- | sort
fi
