#!/usr/bin/env bash

require() { hash "$@" || exit 127; }

require adb

if [ -z "$1" ]; then
  echo "usage: $(basename "$0") message"
  exit 1
fi

TAG=$(basename "$0")

# Priority set to FATAL because otherwise messages seem to be dropped
adb exec-out log -p f -t "$TAG" "$1"
