#!/usr/bin/env bash

require() { hash "$@" || exit 127; }

require adb

if [[ -z "$1" ]]; then
  echo "usage: $(basename "$0") tag" # PowerManagerService ActivityManager
  exit 1
fi

adb logcat -v time "$(printf '*:S %s' "$1")"
