#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0")

Displays battery stats from an adb-connected Android device.

Options:
  --help      Display this help message and exit

Environment:
  ANDROID_SERIAL  Serial number of device to connect to (see 'adb devices -l').
EOF
  exit 0
}

if [[ "$1" == "--help" ]]; then
  usage
fi

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo >&2 "$(basename "$0"): $1 not found"
    exit 127
  }
}

require adb

# https://medium.com/@kalpeshsomani30/android-power-consumption-analysis-c019b9998287
adb exec-out dumpsys batterystats
