#!/usr/bin/env bash

require() { hash "$@" || exit 127; }

require adb

SERVICES=$(adb exec-out dumpsys activity service com.google.android.wearable.healthservices | grep ^SERVICE | awk '{ print $2 }')

for s in $SERVICES; do
  printf "### %s ###\n" "$s"
  echo
  adb exec-out dumpsys activity services "$s" # generic (system) service metadata
  echo
  adb exec-out dumpsys activity service "$s" # service specific debug output
  echo
done
