#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") APK_FILE

Displays 'aapt d badging' information for a given APK.

The script supports both standalone APK files and ZIP archives containing a base split APK.

Arguments:
  APK_FILE    Path to an APK or a ZIP file containing a base split APK.

Options:
  -h, --help  Display this help message and exit

Examples:
  # Display badging information for a standalone APK
  $(basename "$0") /path/to/your/app.apk

  # Display badging information for a ZIP archive
  $(basename "$0") /path/to/your/app.zip
EOF
  exit 0
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
fi

require() { hash "$@" || exit 127; }

require aapt
require unzip

if [ -z "$1" ]; then
  usage
fi

if [ ! -f "$1" ]; then
  echo "$(basename "$0"): $1: No such file or directory" >&2
  exit 1
fi

if [[ $1 == *.zip ]]; then
  TMPDIR=$(mktemp -d)
  trap 'rm -rf -- "$TMPDIR"' EXIT
  unzip -q -j "$1" '*-base-split.apk' -d "$TMPDIR"
  BASEAPKS=("$TMPDIR"/*-base-split.apk)
  BASEAPK="${BASEAPKS[0]}"
  if [ ! -f "$BASEAPK" ]; then
    echo "$(basename "$0"): *-base-split.apk not found in zip, aborting" >&2
    exit 1
  fi
else
  BASEAPK="$1"
fi

aapt d badging "$BASEAPK"
