complete -c caxton -f

complete -c caxton -l read -r -F -d "Make paths visible to the model"
complete -c caxton -l edit -r -F -d "Make paths visible and writable"
complete -c caxton -l read-from -r -F -d "Read further --read paths from a file, or '-' for stdin"
complete -c caxton -l edit-from -r -F -d "Read further --edit paths from a file, or '-' for stdin"
complete -c caxton -s 0 -l null -d "Path list files are NUL-delimited"
complete -c caxton -l inline -r -F -d "Inline only these paths into the initial prompt"
complete -c caxton -l no-inline -d "Inline nothing; the model reads files on demand"
complete -c caxton -s n -l dry-run -d "Print the resolved policy and payload, then exit"
complete -c caxton -l force -d "Bypass safety checks (context threshold, dirty worktree, unrestorable writes)"
complete -c caxton -l model -x -d "Gemini model to use"
complete -c caxton -l thinking -x -a "high low none" -d "Thinking level (default: high)"
complete -c caxton -l search -d "Enable Google Search grounding for external context (default)"
complete -c caxton -l no-search -d "Disable Google Search grounding"
complete -c caxton -l code -d "Enable Python code execution in cloud sandbox (default)"
complete -c caxton -l no-code -d "Disable Python code execution in cloud sandbox"
complete -c caxton -l max-steps -x -d "Maximum agent execution steps (default: 100)"
complete -c caxton -l timeout -x -d "Maximum execution time in seconds (default: 1800)"
complete -c caxton -s h -l help -d "Display help message and exit"
