complete -c git-mirror -s h -l help -d "Display help message and exit"
complete -c git-mirror -s n -l dry-run -d "Perform a trial run with no changes made"
complete -c git-mirror -l all -d "Update all registered mirrors"
complete -c git-mirror -n __fish_use_subcommand -a add -d "Register a named mirror target destination"
complete -c git-mirror -n __fish_use_subcommand -a "remove rm" -d "Unregister a mirror target"
complete -c git-mirror -n __fish_use_subcommand -a list -d "List all registered mirror targets"
complete -c git-mirror -n __fish_use_subcommand -a update -d "Update a registered mirror"
complete -c git-mirror -n "__fish_seen_subcommand_from remove rm update" -a "(git config --local --get-regexp '^mirror\\.target\\.' 2>/dev/null | string replace -r '^mirror\\.target\\.(\\S+).*' '\$1')" -d "Mirror target"
complete -c git-mirror -n "__fish_seen_subcommand_from add" -a "(__fish_complete_directories)" -d "Destination directory"
