# Generated by: gog completion fish
function __gog_complete
  set -l words (commandline -opc)
  set -l cur (commandline -ct)

  # Include the current token (partial word being typed) to match bash behavior.
  set words $words $cur

  # cword points to the last word (the one being completed).
  set -l cword (math (count $words) - 1)
  gog __complete --cword $cword -- $words
end

complete -c gog -f -a "(__gog_complete)"
