#!/usr/bin/env bash
#
# Tests for bin/jetpack-samples

set -u

SCRIPT_DIR=$(dirname "$0")
ROOT_DIR="$SCRIPT_DIR/.."
BIN_JETPACK_SAMPLES="$ROOT_DIR/scripts/jetpack-samples"

TOTAL_TESTS=2
TEST_NUM=0

echo "1..$TOTAL_TESTS"

run_test() {
  local artifact="$1"
  TEST_NUM=$((TEST_NUM + 1))

  OUT_DIR=$(mktemp -d)

  if "$BIN_JETPACK_SAMPLES" "$artifact" --output "$OUT_DIR" >/dev/null 2>&1; then
    if [ ! "$(ls -A "$OUT_DIR")" ]; then
      echo "not ok $TEST_NUM - no files in output dir for $artifact"
    elif [ "$(find "$OUT_DIR" -type d -name "src" | wc -l)" -eq 0 ]; then
      echo "not ok $TEST_NUM - no 'src' directories found for $artifact"
    elif [ "$(find "$OUT_DIR" -name "build.gradle" -o -name "build.gradle.kts" | wc -l)" -eq 0 ]; then
      echo "not ok $TEST_NUM - no build.gradle files found (failed to download complete module archive) for $artifact"
    else
      echo "ok $TEST_NUM - successfully extracted complete samples module for $artifact"
    fi
  else
    echo "not ok $TEST_NUM - failed to run jetpack-samples for $artifact"
  fi
  rm -rf "$OUT_DIR"
}

run_test "androidx.compose.remote:remote-creation-compose"

# Test invalid artifact
TEST_NUM=$((TEST_NUM + 1))
if ! "$BIN_JETPACK_SAMPLES" "invalid-artifact" >/dev/null 2>&1; then
  echo "ok $TEST_NUM - failed on invalid artifact"
else
  echo "not ok $TEST_NUM - accepted invalid artifact"
fi
