#!/bin/bash

# Format staged files before commit

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|md)$')

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs prettier --write --log-level warn
  echo "$STAGED_FILES" | xargs git add
fi
